[package]
name = "redd"
version = "0.1.0"
authors = ["Nick Bryan <nickbryan.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
crossterm = "0.18"
unicode-segmentation = "1.6"

