[package]
name = "vie_tui"
version = "0.1.0"
authors = ["Nick Bryan <nickbryan.dev@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
crossterm = "0.18"
vie_core = { version = "0.1.0", path = "../vie_core" }
